# This Dockerfile is used to let Dependabot manage the pinned version of Python 3.12
# that will be installed into the docker container.

# This file is separate from the other Dockerfile tools in order to create a separate
# entry in the Dependabot config that ignores major and minor version updates, in
# order to keep this pinned to Python 3.12.

FROM python:3.12.12 as python312
